/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "i2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(I2CReadWriteRequest, I2CReadWriteRequest, 4)


PB_BIND(I2CReadWriteResponse, I2CReadWriteResponse, 4)





