/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "spi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SPIReadWriteRequest, SPIReadWriteRequest, 4)


PB_BIND(SPIReadWriteResponse, SPIReadWriteResponse, 4)









